### ISSUE TITLE
.ENV issue

### ISSUE THREAD

**Issue by Rivalakmalll** [aulianza/aulianza.id#326]
hei i love you code but i need to more information to getting .env token the env sourece how to get token from can you send it to me? thx

**Comment by aulianza** [comment]
which env token exactly?

**Comment by Rivalakmalll** [comment]
> which env token exactly? @Rivalakmalll 

Like everything source web need to setup the .env

**Comment by aulianza** [comment]
You can find it from every service provider's official documentations, such as Spotify, Wakatime, Firebase and so on. 
for example for spotify: https://developer.spotify.com/

**Comment by Rivalakmalll** [comment]
> You can find it from every service provider's official documentations, such as Spotify, Wakatime, Firebase and so on. 
> for example for spotify: https://developer.spotify.com/

What About this .env where i can find this api  source web  url from to i put in env

# Blog
BLOG_API_URL=

# OpenAI
OPENAI_API_KEY=

# DEV.to
DEVTO_KEY=


# GitHub
GITHUB_READ_USER_TOKEN_PERSONAL=
GITHUB_READ_USER_TOKEN_WORK=



# Contact Form
CONTACT_FORM_API_KEY=

**Comment by Rivalakmalll** [comment]
Hei how i can deployment this web? I cant deploy use u say in read.me can u help me? @aulianza
